# Generated by Django 4.0.2 on 2022-02-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
