# Generated by Django 4.0.2 on 2022-02-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_drink_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='description',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='drink',
            name='english_name',
            field=models.CharField(max_length=50),
        ),
    ]
