# Generated by Django 4.0.2 on 2022-02-12 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_drink_description_alter_drink_english_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'allergies',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('size_ml', models.CharField(max_length=20, null=True)),
                ('size_fluid_ounce', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'sizes',
            },
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_serving_kal', models.DecimalField(decimal_places=3, max_digits=10)),
                ('sodium_mg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('saturated_fat_g', models.DecimalField(decimal_places=3, max_digits=10)),
                ('sugars_g', models.DecimalField(decimal_places=3, max_digits=10)),
                ('protein_g', models.DecimalField(decimal_places=3, max_digits=10)),
                ('caffeine_mg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('drink_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.drink')),
                ('size_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.size')),
            ],
            options={
                'db_table': 'nutritions',
            },
        ),
        migrations.CreateModel(
            name='Allergy_drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.allergy')),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.drink')),
            ],
            options={
                'db_table': 'allergies_dirnks',
            },
        ),
    ]
