# Generated by Django 4.0.2 on 2022-02-12 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_allergy_size_nutrition_allergy_drink'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='allergy_drink',
            table='allergies_drinks',
        ),
    ]
